### PR TITLE
erfadatextra.h `#ifndef`

### PR DESCRIPTION
**Pull request by RocketRoss**
Enables source_flattener.py to scrape until #endif and succeed.

### CODE REVIEW

**Comment by mhvk** [comment]
@RocketRoss - that looks good and makes sense - we really should have had that (just goes to show how poor my C is...)

Will just check that the tests pass - but I don't see how they could not!

**Comment by RocketRoss** [comment]
Just the smallest oversight, happy to help patch. Only came up because of the flatten_sources.py if erfa_fetch. Thanks!

**Comment by mhvk** [comment]
@RocketRoss - just noticed something silly, but might as well fix it - there is a missing new-line at the end of the file. Could you fix that? (Happy to do it myself if that's easier)

**Comment by RocketRoss** [comment]
Sorted 👍

**Comment by avalentino** [comment]
@mhvk I think that you need to approve the test execution in order to run tests

**Comment by mhvk** [comment]
@RocketRoss - thanks! Will merge once tests have run again.

**Comment by RocketRoss** [comment]
@mhvk Success :)

**Pull request merged**
