### PR TITLE
Update following SOFA 20231011

### LINKED ISSUE #96: Need to update to SOFA 19
SOFA 19 was released 2023 Oct 11.

### PR DESCRIPTION
**Pull request by mhvk**
Fixes #96

### CODE REVIEW

**Comment by mhvk** [comment]
@sergiopasra - would you be able to review this erfa update? There isn't really much to it!

**Comment by mhvk** [comment]
p.s. I'll make a release of this once it is in.

**Review by avalentino — APPROVED** [review]

**Comment by sergiopasra** [comment]
I arrive to this too late, sorry

**Comment by mhvk** [comment]
No worries, a day after really is not too late! (Though perhaps you would have caught that I hadn't updated `configure.ac`, which is actually still needed...)

**Comment by sergiopasra** [comment]
Now that I see the tarball, it doesn't contain `configure`, so if you try to build without meson, you have to run `bootstrap.sh` and you need `automake`, `autoconf`... the full autotools stack

**Comment by mhvk** [comment]
> Now that I see the tarball, it doesn't contain `configure`, so if you try to build without meson, you have to run `bootstrap.sh` and you need `automake`, `autoconf`... the full autotools stack

I think that was always the case - at least in `pyerfa`, we run `bootstrap.sh` in `setup.py` if `config.h` is not present.

**Comment by sergiopasra** [comment]
@mhvk At least the last release had a  `configure`. The file is meant to be distributed (but you can run `bootstrap.sh` if you want)

**Comment by mhvk** [comment]
Hmm, I guess with your #5, the old `make distcheck` added it to the distribution - and this is no longer done with `meson`. If we still want to include it, I guess we should update the release procedures: it does seem like `RELEASE.rst` was edited a bit too rigorously in #90 (I already added back in that one needed to edit `configure.ac`). I'm not quite sure what would be needed. Maybe start with a new issue to discuss?

**Comment by eli-schwartz** [comment]
Sorry for being incredibly late to the party...  in meson you can use: https://mesonbuild.com/Reference-manual_builtin_meson.html#mesonadd_dist_script

```meson
meson.add_dist_script('./bootstrap.sh')
```

**Pull request merged**
